collectd:
  reload_cmd: 'sudo /etc/init.d/collectd restart'
  stats:
    ping: #Configuration for ping-graphs
      type: PingStat
      dir: '/var/lib/collectd/rrd/stats.ffm.freifunk.net'
      address: '<%= node.link_local %>%backbone-stats.rrd'  
#    ping: #Configuration for ping-graphs
#      type: PingStat
#      dir: '/var/lib/collectd/rrd/freifunk-<%= node.id_hex%>'
#      address: 'stats.bb6.ffm.freifunk.net.rrd'  
    interface: #Configuration for interface-graphs
      type: InterfaceRxTxStat
      dir: '/var/lib/collectd/rrd/freifunk-<%= @node.id_hex%>/'
    error: #Configuration for interface-graphs
      type: InterfaceErrorStat
      dir: '/var/lib/collectd/rrd/freifunk-<%= @node.id_hex%>/'
    iwinfo:
      type: IwinfoStat
      dir: '/var/lib/collectd/rrd/freifunk-<%= @node.id_hex%>/'

  ping:
    template: './templates/ping.conf.erb'
    path: '/etc/collectd/mesh-conf/ping.conf'
    interface: 'backbone-stats'
